const key="lee-family-state";
const today=new Date(); const iso=d=>new Date(d).toISOString().slice(0,10); const state=JSON.parse(localStorage.getItem(key)||"null")||{
  ingredients:[{id:1,name:"배추",emoji:"🥬",place:"냉장실",qty:"1통",expiry:"2026-10-03"},{id:2,name:"계란",emoji:"🥚",place:"냉장실",qty:"10개",expiry:"2026-10-10"},{id:3,name:"소고기",emoji:"🥩",place:"냉동실",qty:"300g",expiry:"2026-09-26"},{id:4,name:"방울토마토",emoji:"🍅",place:"냉장실",qty:"1팩",expiry:"2026-09-30"}],
  events:[{id:1,title:"병원",date:"2026-09-28",time:"14:00",owner:"수희"},{id:2,title:"아빠 회의",date:"2026-09-29",time:"10:00",owner:"아빠"}],
  chores:[{id:1,title:"거실 청소기 돌리기",owner:"수희",due:"오늘",repeat:"없음",done:false},{id:2,title:"화분 물주기",owner:"수희",due:"오늘",repeat:"3일마다",done:false},{id:3,title:"분리수거 배출",owner:"동생",due:"오늘",repeat:"매주",done:true}],
  notices:[{id:1,title:"이번 주 토요일 가족 식사",body:"저녁 6시에 함께 식사해요.",owner:"엄마",private:false},{id:2,title:"생일 선물 준비 안내",body:"비밀번호를 아는 가족만 확인해주세요.",owner:"아빠",private:true,password:"1234"},{id:3,title:"이번 달 관리비 확인해주세요",body:"이번 달 관리비를 확인했습니다.",owner:"엄마",private:false}]
}; let view="dashboard"; const save=()=>localStorage.setItem(key,JSON.stringify(state)); const esc=s=>String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
const dday=x=>{const n=Math.ceil((new Date(x)-new Date(iso(today)))/86400000);return n<0?"기한 지남":`D-${n}`}; const isBad=x=>new Date(x)<new Date(iso(today));
function theme(){const m=today.getMonth()+1;const t=m>=3&&m<=5?["#d97793","#b95270","#fdebf0","봄 / Flushing Pink"]:m>=6&&m<=8?["#5c91b8","#3f6f91","#e9f3fb","여름 / Blue Frost"]:m>=9&&m<=11?["#b46b7d","#8f4d62","#f9e9ed","가을 / Chicory Coffee"]:["#71808b","#53626d","#edf0f2","겨울 / Gargoyle"];document.documentElement.style.setProperty("--accent",t[0]);document.documentElement.style.setProperty("--accent-strong",t[1]);document.documentElement.style.setProperty("--accent-soft",t[2]);document.querySelector(".footer-note")?.replaceChildren(`현재 테마 · ${t[3]} · ${m}월`)}
function layout(){theme();document.querySelectorAll(".nav-item").forEach(b=>b.classList.toggle("active",b.dataset.view===view));const titles={dashboard:["안녕하세요, 이수희님","오늘도 우리 가족의 하루를 한눈에 확인해보세요."],fridge:["냉장고 관리","재료의 상태와 유통기한을 관리해보세요."],schedule:["가족 일정","가족 구성원별 일정을 한곳에서 확인하세요."],chores:["집안일 TO-DO","반복되는 집안일까지 놓치지 않도록 관리하세요."],notices:["공지사항","가족에게 전할 이야기를 남겨보세요." ]};document.getElementById("page-title").textContent=titles[view][0];document.getElementById("page-subtitle").textContent=titles[view][1];document.getElementById("today-label").textContent=today.toLocaleDateString("en-US",{weekday:"long",month:"long",day:"numeric"}).toUpperCase();document.getElementById("app-view").innerHTML=views[view]();bind()}
const views={dashboard:()=>`<section class="grid"><article class="card fridge-card"><div class="card-header"><div class="card-title">냉장고 현황</div><button class="link-btn" data-go="fridge">전체 보기 →</button></div><div class="fridge-summary"><div><b>${state.ingredients.length}</b><span>개의 재료가 있어요</span></div><div class="fridge-temp"><strong>냉장 3.8℃</strong>마지막 업데이트 오늘</div></div>${state.ingredients.slice(0,5).map(ingredient).join("")}<button class="add-btn" data-modal="ingredient">＋ 재료 추가하기</button><div class="calendar"><div class="calendar-head"><strong>이번 주 가족 일정</strong><button data-go="schedule">캘린더 보기 →</button></div>${calendar()}</div></article><article class="card"><div class="card-header"><div class="card-title">오늘의 집안일</div><button class="link-btn" data-go="chores">관리 →</button></div>${state.chores.slice(0,4).map(chore).join("")}<button class="add-btn" data-modal="chore">＋ 할 일 추가하기</button></article><article class="card"><div class="card-header"><div class="card-title">공지사항</div><button class="link-btn" data-go="notices">전체 보기 →</button></div>${state.notices.slice(0,3).map(notice).join("")}</article></section><div class="footer-note"></div>`,
fridge:()=>`<section class="page-grid"><article class="card wide"><div class="toolbar"><h2>냉장고 재료 <small class="muted">(${state.ingredients.length})</small></h2><button class="primary" data-modal="ingredient">＋ 재료 추가</button></div><div class="table-list">${state.ingredients.map(ingredientRow).join("")||`<div class="empty">등록된 재료가 없습니다.</div>`}</div></article><article class="card"><div class="card-title">냉장고 사진</div><p class="subtitle">최대 4장까지 올릴 수 있어요. 사진 기반 재료 인식은 다음 단계에서 연결할 수 있습니다.</p><button class="add-btn" data-photo>＋ 사진 선택하기</button></article><article class="card"><div class="card-title">추천 메뉴</div><p class="subtitle">현재 재료를 바탕으로 메뉴를 탐색해보세요.</p><div class="filters">${["한식","중식","양식","일식","간편식"].map(x=>`<button class="mini">${x}</button>`).join("")}</div><p><b>배추 · 계란 · 소고기</b>로 만들 수 있는 메뉴</p><div class="row"><span>🍲</span><div class="row-main"><b>소고기 배추 전골</b><small>한식 · 재료 3개 사용</small></div></div></article></section><div class="footer-note"></div>`,
schedule:()=>`<section class="page-grid"><article class="card wide"><div class="toolbar"><h2>가족 일정</h2><button class="primary" data-modal="event">＋ 일정 추가</button></div>${calendar(true)}</article><article class="card wide"><div class="card-title">등록된 일정</div><div class="table-list">${state.events.map(e=>`<div class="row"><span>📅</span><div class="row-main"><b>${esc(e.title)}</b><small>${e.date} ${e.time||""} · ${esc(e.owner)}</small></div><div class="row-actions"><button class="mini" data-delete="event" data-id="${e.id}">삭제</button></div></div>`).join("")||`<div class="empty">등록된 일정이 없습니다.</div>`}</div></article></section><div class="footer-note"></div>`,
chores:()=>`<section class="page-grid"><article class="card wide"><div class="toolbar"><h2>집안일 TO-DO</h2><button class="primary" data-modal="chore">＋ 할 일 추가</button></div><div class="table-list">${state.chores.map(choreRow).join("")||`<div class="empty">등록된 일이 없습니다.</div>`}</div></article></section><div class="footer-note"></div>`,
notices:()=>{const page=Math.max(1,Number(window.noticePage||1)),items=state.notices.slice((page-1)*10,page*10);return `<section class="page-grid"><article class="card wide"><div class="toolbar"><h2>공지사항</h2><button class="primary" data-modal="notice">＋ 글쓰기</button></div><div class="table-list">${items.map(noticeRow).join("")||`<div class="empty">등록된 공지가 없습니다.</div>`}</div><div class="filters" style="justify-content:center;margin-top:16px">${Array.from({length:Math.max(1,Math.ceil(state.notices.length/10))},(_,i)=>`<button class="mini" data-page="${i+1}">${i+1}</button>`).join("")}</div></article></section><div class="footer-note"></div>`}};
function ingredient(i){return `<div class="ingredient"><div class="food">${i.emoji||"🥕"}</div><div class="ingredient-main"><b>${esc(i.name)}</b><span>${esc(i.place)} · ${esc(i.qty)}</span></div><div class="expiry ${isBad(i.expiry)?"bad":""}">${dday(i.expiry)}</div></div>`}
function ingredientRow(i){return `<div class="row"><div class="food">${i.emoji||"🥕"}</div><div class="row-main"><b>${esc(i.name)}</b><small>${esc(i.place)} · ${esc(i.qty)} · ${i.expiry}</small></div><strong class="expiry ${isBad(i.expiry)?"bad":""}">${dday(i.expiry)}</strong><button class="mini" data-delete="ingredient" data-id="${i.id}">삭제</button></div>`}
function chore(c){return `<div class="todo ${c.done?"done":""}" data-toggle="${c.id}"><div class="check"></div><b>${esc(c.title)}</b><small>${esc(c.owner)}</small></div>`}
function choreRow(c){return `<div class="row"><div class="check" data-toggle="${c.id}"></div><div class="row-main"><b>${esc(c.title)}</b><small>담당 ${esc(c.owner)} · 기한 ${esc(c.due)} · ${esc(c.repeat)}</small></div><button class="mini" data-delete="chore" data-id="${c.id}">삭제</button></div>`}
function notice(n){return `<div class="notice"><div class="notice-pin">${n.private?"🔒":"📌"}</div><div><b>${esc(n.title)}</b><span>${esc(n.owner)} · ${n.private?"비공개":"전체 공개"}</span></div></div>`}
function noticeRow(n){return `<div class="row"><div class="notice-pin">${n.private?"🔒":"📌"}</div><div class="row-main"><b>${esc(n.title)}</b><small>${esc(n.owner)} · ${n.private?"비밀번호 보호":"전체 공개"}</small></div><button class="mini" data-view-notice="${n.id}">열기</button><button class="mini" data-delete="notice" data-id="${n.id}">삭제</button></div>`}
function calendar(full=false){const ev=state.events;return `<div class="week">${["월","화","수","목","금","토","일"].map(x=>`<div class="day day-name">${x}</div>`).join("")}${[28,29,30,1,2,3,4].map((n,i)=>`<div class="day ${i===0?"today":""}"><div class="day-num">${n}</div>${ev.filter(e=>e.date===`2026-09-${String(n).padStart(2,"0")}`).map(e=>`<div class="event ${e.owner==="수희"?"pink":"green"}">${esc(e.title)} ${e.time||""}</div>`).join("")}</div>`).join("")}</div>`}
function modal(type){const fields={ingredient:`<label>재료명<input name="name" required placeholder="예: 양파"></label><label>수량<input name="qty" required placeholder="예: 2개"></label><label>보관 위치<select name="place"><option>냉장실</option><option>냉동실</option><option>실온</option></select></label><label>유통기한<input name="expiry" type="date" required></label>`,event:`<label>일정 제목<input name="title" required></label><label>날짜<input name="date" type="date" required value="${iso(today)}"></label><label>시간<input name="time" type="time"></label><label>담당자<select name="owner"><option>수희</option><option>엄마</option><option>아빠</option><option>동생</option></select></label>`,chore:`<label>할 일<input name="title" required placeholder="예: 화분 물주기"></label><label>담당자<select name="owner"><option>수희</option><option>엄마</option><option>아빠</option><option>동생</option></select></label><label>기한<input name="due" value="오늘"></label><label>주기<select name="repeat"><option>없음</option><option>매일</option><option>3일마다</option><option>매주</option><option>매월</option></select></label>`,notice:`<label>제목<input name="title" required></label><label>내용<textarea name="body" required></textarea></label><label>작성자<select name="owner"><option>수희</option><option>엄마</option><option>아빠</option><option>동생</option></select></label><label><input name="private" type="checkbox"> 비밀번호 보호</label><label>비밀번호<input name="password" placeholder="비공개 글인 경우 입력"></label>`};document.getElementById("modal-root").innerHTML=`<div class="modal-backdrop"><div class="modal"><h2>${type==="ingredient"?"재료 추가":type==="event"?"일정 추가":type==="chore"?"집안일 추가":"공지사항 작성"}</h2><form class="form" data-form="${type}">${fields[type]}<div class="modal-actions"><button type="button" class="secondary" data-close>취소</button><button class="primary">저장</button></div></form></div></div>`}
function bind(){document.querySelectorAll("[data-go]").forEach(b=>b.onclick=()=>{view=b.dataset.go;layout()});document.querySelectorAll("[data-modal]").forEach(b=>b.onclick=()=>modal(b.dataset.modal));document.querySelectorAll("[data-toggle]").forEach(b=>b.onclick=()=>{const c=state.chores.find(x=>x.id==b.dataset.toggle);if(c){c.done=!c.done;save();layout()}});document.querySelectorAll("[data-delete]").forEach(b=>b.onclick=()=>{const k={ingredient:"ingredients",event:"events",chore:"chores",notice:"notices"}[b.dataset.delete];state[k]=state[k].filter(x=>x.id!=b.dataset.id);save();layout()});document.querySelectorAll("[data-page]").forEach(b=>b.onclick=()=>{window.noticePage=b.dataset.page;layout()});document.querySelectorAll("[data-view-notice]").forEach(b=>b.onclick=()=>{const n=state.notices.find(x=>x.id==b.dataset.viewNotice);if(n.private&&prompt("비밀번호를 입력하세요")!==n.password)return alert("비밀번호가 올바르지 않습니다.");alert(`${n.title}\n\n${n.body}`)});document.querySelectorAll("[data-photo]").forEach(b=>b.onclick=()=>alert("사진 선택 기능은 현재 UI 흐름이 연결되어 있습니다. 실제 저장/AI 인식은 다음 단계에서 연결합니다."));const form=document.querySelector("[data-form]");if(form)form.onsubmit=e=>{e.preventDefault();const d=Object.fromEntries(new FormData(form));const type=form.dataset.form;if(type==="ingredient")state.ingredients.push({id:Date.now(),emoji:"🥕",...d});if(type==="event")state.events.push({id:Date.now(),...d});if(type==="chore")state.chores.push({id:Date.now(),done:false,...d});if(type==="notice")state.notices.unshift({id:Date.now(),private:form.private.checked,...d});save();document.getElementById("modal-root").innerHTML="";layout()};document.querySelector("[data-close]")?.addEventListener("click",()=>document.getElementById("modal-root").innerHTML="")}
document.getElementById("main-nav").onclick=e=>{const b=e.target.closest("[data-view]");if(b){view=b.dataset.view;layout()}};layout();
