const key="lee-family-state";
const today=new Date(); const localDate=d=>new Date(d.getFullYear(),d.getMonth(),d.getDate()); const dateValue=value=>typeof value==="string"&&/^\d{4}-\d{2}-\d{2}$/.test(value)?new Date(Number(value.slice(0,4)),Number(value.slice(5,7))-1,Number(value.slice(8,10))):localDate(value instanceof Date?value:new Date(value)); const iso=d=>{const date=dateValue(d);return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}-${String(date.getDate()).padStart(2,"0")}`}; const state=JSON.parse(localStorage.getItem(key)||"null")||{
  ingredients:[{id:1,name:"배추",emoji:"🥬",place:"냉장실",qty:"1통",expiry:"2026-10-03"},{id:2,name:"계란",emoji:"🥚",place:"냉장실",qty:"10개",expiry:"2026-10-10"},{id:3,name:"소고기",emoji:"🥩",place:"냉동실",qty:"300g",expiry:"2026-09-26"},{id:4,name:"방울토마토",emoji:"🍅",place:"냉장실",qty:"1팩",expiry:"2026-09-30"}],
  events:[{id:1,title:"병원",date:"2026-09-28",time:"14:00",owner:"수희"},{id:2,title:"아빠 회의",date:"2026-09-29",time:"10:00",owner:"아빠"}],
  chores:[{id:1,title:"거실 청소기 돌리기",owner:"수희",due:"오늘",repeat:"없음",done:false},{id:2,title:"화분 물주기",owner:"수희",due:"오늘",repeat:"3일마다",done:false},{id:3,title:"분리수거 배출",owner:"동생",due:"오늘",repeat:"매주",done:true}],
  notices:[{id:1,title:"이번 주 토요일 가족 식사",body:"저녁 6시에 함께 식사해요.",owner:"엄마",private:false},{id:2,title:"생일 선물 준비 안내",body:"비밀번호를 아는 가족만 확인해주세요.",owner:"아빠",private:true,password:"1234"},{id:3,title:"이번 달 관리비 확인해주세요",body:"이번 달 관리비를 확인했습니다.",owner:"엄마",private:false}]
}; const familyMembers=[{name:"수희",avatar:"수희",className:"av3"},{name:"엄마",avatar:"엄마",className:"av1"},{name:"아빠",avatar:"아빠",className:"av2"},{name:"동생",avatar:"동생",className:"av4"}]; const memberName=owner=>owner==="나"?"수희":owner; let view="dashboard"; let recentlyAddedId=null; const save=()=>localStorage.setItem(key,JSON.stringify(state)); const esc=s=>String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
const dday=x=>{const n=Math.ceil((dateValue(x)-localDate(today))/86400000);return n<0?"기한 지남":`D-${n}`}; const isBad=x=>dateValue(x)<localDate(today);
function theme(){const m=today.getMonth()+1;const t=m>=3&&m<=5?["#d97793","#b95270","#fdebf0","봄 / Flushing Pink"]:m>=6&&m<=8?["#5c91b8","#3f6f91","#e9f3fb","여름 / Blue Frost"]:m>=9&&m<=11?["#b46b7d","#8f4d62","#f9e9ed","가을 / Chicory Coffee"]:["#71808b","#53626d","#edf0f2","겨울 / Gargoyle"];document.documentElement.style.setProperty("--accent",t[0]);document.documentElement.style.setProperty("--accent-strong",t[1]);document.documentElement.style.setProperty("--accent-soft",t[2]);document.querySelector(".footer-note")?.replaceChildren(`현재 테마 · ${t[3]} · ${m}월`)}
function layout(){theme();document.querySelectorAll(".nav-item").forEach(b=>b.classList.toggle("active",b.dataset.view===view));const titles={dashboard:["안녕하세요, 이수희님","오늘도 우리 가족의 하루를 한눈에 확인해보세요."],fridge:["냉장고 관리","재료의 상태와 유통기한을 관리해보세요."],schedule:["가족 일정","가족 구성원별 일정을 한곳에서 확인하세요."],chores:["집안일 TO-DO LIST","반복되는 집안일까지 놓치지 않도록 관리하세요."],notices:["공지사항","가족에게 전할 이야기를 남겨보세요." ]};document.getElementById("page-title").textContent=titles[view][0];document.getElementById("page-subtitle").textContent=titles[view][1];document.getElementById("today-label").textContent=today.toLocaleDateString("en-US",{weekday:"long",month:"long",day:"numeric"}).toUpperCase();document.getElementById("app-view").innerHTML=views[view]();bind()}
const views={dashboard:()=>`<section class="grid"><article class="card fridge-card"><div class="card-header"><div class="card-title">냉장고 현황</div><button class="link-btn" data-go="fridge">전체 보기 →</button></div><div class="fridge-summary"><div><b>${state.ingredients.length}</b><span>개의 재료가 있어요</span></div><div class="fridge-temp"><strong>냉장 3.8℃</strong>마지막 업데이트 오늘</div></div>${state.ingredients.slice(0,5).map(ingredient).join("")}<button class="add-btn" data-modal="ingredient">＋ 재료 추가하기</button><div class="calendar"><div class="calendar-head"><strong>이번 주 가족 일정</strong><button data-go="schedule">캘린더 보기 →</button></div>${calendar()}</div></article><article class="card"><div class="card-header"><div class="card-title">집안일 TO-DO LIST</div><button class="link-btn" data-go="chores">관리 →</button></div>${state.chores.slice(0,4).map(chore).join("")}<button class="add-btn" data-modal="chore">＋ 집안일 TO-DO LIST 추가</button></article><article class="card"><div class="card-header"><div class="card-title">공지사항</div><button class="link-btn" data-go="notices">전체 보기 →</button></div>${state.notices.slice(0,3).map(notice).join("")}</article></section><div class="footer-note"></div>`,
fridge:()=>`<section class="page-grid"><article class="card wide"><div class="toolbar"><div><h2>냉장고 재료 <small class="muted">(${state.ingredients.length})</small></h2><p class="subtitle">보관 위치를 기준으로 한눈에 확인해보세요.</p></div><button class="primary" data-modal="ingredient">＋ 재료 추가</button></div>${fridgeVisual()}</article><article class="card"><div class="card-title">냉장고 사진</div><p class="subtitle">최대 4장까지 올릴 수 있어요. 사진 기반 재료 인식은 다음 단계에서 연결할 수 있습니다.</p><button class="add-btn" data-photo>＋ 사진 선택하기</button></article><article class="card"><div class="card-title">추천 메뉴</div><p class="subtitle">현재 재료를 바탕으로 메뉴를 탐색해보세요.</p><div class="filters">${["한식","중식","양식","일식","간편식"].map(x=>`<button class="mini">${x}</button>`).join("")}</div><p><b>배추 · 계란 · 소고기</b>로 만들 수 있는 메뉴</p><div class="row"><span>🍲</span><div class="row-main"><b>소고기 배추 전골</b><small>한식 · 재료 3개 사용</small></div></div></article></section><div class="footer-note"></div>`,
schedule:()=>`<section class="page-grid"><article class="card wide"><div class="toolbar"><h2>가족 일정</h2><button class="primary" data-modal="event">＋ 일정 추가</button></div>${calendar(true)}</article><article class="card wide"><div class="card-title">등록된 일정</div><div class="table-list">${state.events.map(e=>`<div class="row"><span>📅</span><div class="row-main"><b>${esc(e.title)}</b><small>${e.date} ${e.time||""} · ${esc(e.owner)}</small></div><div class="row-actions"><button class="mini" data-delete="event" data-id="${e.id}">삭제</button></div></div>`).join("")||`<div class="empty">등록된 일정이 없습니다.</div>`}</div></article></section><div class="footer-note"></div>`,
chores:()=>`<section class="page-grid"><article class="card wide"><div class="toolbar"><h2>집안일 TO-DO LIST</h2><button class="primary" data-modal="chore">＋ 집안일 TO-DO LIST 추가</button></div><div class="chore-groups">${familyMembers.map(choreGroup).join("")}</div></article></section><div class="footer-note"></div>`,
notices:()=>{const page=Math.max(1,Number(window.noticePage||1)),items=state.notices.slice((page-1)*10,page*10);return `<section class="page-grid"><article class="card wide"><div class="toolbar"><h2>공지사항</h2><button class="primary" data-modal="notice">＋ 글쓰기</button></div><div class="table-list">${items.map(noticeRow).join("")||`<div class="empty">등록된 공지가 없습니다.</div>`}</div><div class="filters" style="justify-content:center;margin-top:16px">${Array.from({length:Math.max(1,Math.ceil(state.notices.length/10))},(_,i)=>`<button class="mini" data-page="${i+1}">${i+1}</button>`).join("")}</div></article></section><div class="footer-note"></div>`}};
function ingredient(i){return `<div class="ingredient ${recentlyAddedId==i.id?"is-recent":""}" ${recentlyAddedId==i.id?'aria-live="polite"':""}><div class="food">${esc(i.emoji||"🥕")}</div><div class="ingredient-main"><b>${esc(i.name)}</b><span>${esc(i.place)} · ${esc(i.qty)}</span></div><div class="expiry ${isBad(i.expiry)?"bad":""}">${dday(i.expiry)}</div></div>`}
function fridgeVisual(){const groups=[["냉장실","fridge-cooler","냉장 · 3.8℃","선반 3개"],["냉동실","fridge-freezer","냉동 · -18℃","서랍 2개"],["실온","fridge-door","도어 수납","문칸 3개"]];return `<div class="fridge-visual" aria-label="보관 위치별 냉장고"><div class="fridge-body">${groups.map(([place,kind,temp,detail])=>{const items=state.ingredients.filter(i=>i.place===place);return `<section class="fridge-compartment ${kind}" aria-label="${esc(place)}"><div class="compartment-head"><div><b>${esc(place)}</b><span>${esc(temp)}</span></div><small>${esc(detail)}</small></div><div class="compartment-items">${items.map(fridgeItem).join("")||`<div class="compartment-empty">보관 중인 재료가 없어요</div>`}</div></section>`}).join("")}</div><div class="fridge-seal" aria-hidden="true"></div></div>`}
function fridgeItem(i){return `<div class="fridge-item ${recentlyAddedId==i.id?"is-recent":""}" title="${esc(i.name)}" ${recentlyAddedId==i.id?'aria-live="polite"':""}><span class="fridge-item-food">${esc(i.emoji||"🥕")}</span><span class="fridge-item-info"><b>${esc(i.name)}</b><small>${esc(i.qty)} · ${dday(i.expiry)}</small></span></div>`}
function ingredientRow(i){return `<div class="row ${recentlyAddedId==i.id?"is-recent":""}"><div class="food">${esc(i.emoji||"🥕")}</div><div class="row-main"><b>${esc(i.name)}</b><small>${esc(i.place)} · ${esc(i.qty)} · ${esc(i.expiry)}</small></div><strong class="expiry ${isBad(i.expiry)?"bad":""}">${dday(i.expiry)}</strong><button class="mini" data-delete="ingredient" data-id="${esc(i.id)}">삭제</button></div>`}
function chore(c){return `<div class="todo ${c.done?"done":""}" data-toggle="${c.id}"><div class="check"></div><b>${esc(c.title)}</b><small>${esc(memberName(c.owner))}</small></div>`}
function choreGroup(member){const chores=state.chores.filter(c=>memberName(c.owner)===member.name);return `<section class="chore-member"><div class="chore-member-header"><span class="chore-avatar ${member.className}" aria-hidden="true">${esc(member.avatar)}</span><div><h3>${esc(member.name)}</h3><span>${chores.length}개의 할 일</span></div></div><div class="table-list">${chores.map(choreRow).join("")||`<div class="empty">등록된 일이 없습니다.</div>`}</div></section>`}
function choreRow(c){return `<div class="row"><div class="check ${c.done?"done":""}" data-toggle="${c.id}" aria-label="${c.done?"완료됨":"미완료"}"></div><div class="row-main"><b>${esc(c.title)}</b><small>담당 ${esc(memberName(c.owner))} · 기한 ${esc(c.due)} · ${esc(c.repeat)}</small></div><button class="mini" data-delete="chore" data-id="${c.id}">삭제</button></div>`}
function isImportant(n){return n.important===true||n.important==="true"||n.important===1}
function notice(n){return `<div class="notice ${isImportant(n)?"important":""}"><div class="notice-pin">${n.private?"🔒":"📌"}</div><div><b>${esc(n.title)}</b><span>${esc(n.owner)} · ${n.private?"비공개":"전체 공개"}</span></div></div>`}
function noticeRow(n){return `<div class="row notice-row ${isImportant(n)?"important":""}"><div class="notice-pin">${n.private?"🔒":"📌"}</div><div class="row-main"><b>${esc(n.title)}</b><small>${esc(n.owner)} · ${n.private?"비밀번호 보호":"전체 공개"}</small></div><button class="mini" data-view-notice="${n.id}">열기</button><button class="mini" data-delete="notice" data-id="${n.id}">삭제</button></div>`}
function eventColor(owner){return ({수희:"pink",엄마:"blue",아빠:"green",동생:"orange"}[owner]||"purple")}
function eventMarkup(e){return `<div class="event ${eventColor(e.owner)}" title="${esc(`${e.title}${e.time?` ${e.time}`:""}`)}">${esc(e.title)}${e.time?` ${esc(e.time)}`:""}</div>`}
function calendar(full=false){const ev=state.events;const weekdays=["월","화","수","목","금","토","일"];if(!full){const start=localDate(today);start.setDate(start.getDate()-(start.getDay()+6)%7);const days=Array.from({length:7},(_,i)=>{const date=new Date(start);date.setDate(start.getDate()+i);return date});return `<div class="week" aria-label="이번 주 가족 일정">${weekdays.map(x=>`<div class="day day-name">${x}</div>`).join("")}${days.map(date=>`<div class="day ${iso(date)===iso(today)?"today":""}"><div class="day-num">${date.getDate()}</div>${ev.filter(e=>e.date===iso(date)).map(eventMarkup).join("")}</div>`).join("")}</div>`}
const first=new Date(today.getFullYear(),today.getMonth(),1);const last=new Date(today.getFullYear(),today.getMonth()+1,0);const leading=(first.getDay()+6)%7;const total=Math.ceil((leading+last.getDate())/7)*7;const days=Array.from({length:total},(_,i)=>{const date=new Date(today.getFullYear(),today.getMonth(),i-leading+1);return date});const currentWeekStart=localDate(today);currentWeekStart.setDate(currentWeekStart.getDate()-(currentWeekStart.getDay()+6)%7);const currentWeekEnd=new Date(currentWeekStart);currentWeekEnd.setDate(currentWeekStart.getDate()+6);return `<div class="month-calendar" aria-label="${today.getFullYear()}년 ${today.getMonth()+1}월 가족 일정"><div class="month-heading"><strong>${today.getFullYear()}년 ${today.getMonth()+1}월</strong><div class="event-legend">${[["수희","pink"],["엄마","blue"],["아빠","green"],["동생","orange"]].map(([owner,color])=>`<span><i class="legend-dot ${color}"></i>${owner}</span>`).join("")}</div></div><div class="month-grid">${weekdays.map(x=>`<div class="day day-name">${x}</div>`).join("")}${days.map(date=>{const current=iso(date)===iso(today);const inCurrentWeek=date>=currentWeekStart&&date<=currentWeekEnd;return `<div class="day ${date.getMonth()!==today.getMonth()?"other-month ":""}${inCurrentWeek?"current-week ":""}${current?"today":""}"><div class="day-num">${date.getDate()}</div>${ev.filter(e=>e.date===iso(date)).map(eventMarkup).join("")}</div>`}).join("")}</div></div>`}
function modal(type){const fields={ingredient:`<label>재료명<input name="name" required placeholder="예: 양파"></label><label>수량<input name="qty" required placeholder="예: 2개"></label><label>보관 위치<select name="place"><option>냉장실</option><option>냉동실</option><option>실온</option></select></label><label>유통기한<input name="expiry" type="date" required></label>`,event:`<label>일정 제목<input name="title" required></label><label>날짜<input name="date" type="date" required value="${iso(today)}"></label><label>시간<input name="time" type="time"></label><label>담당자<select name="owner"><option>수희</option><option>엄마</option><option>아빠</option><option>동생</option></select></label>`,chore:`<label>할 일<input name="title" required placeholder="예: 화분 물주기"></label><label>담당자<select name="owner">${familyMembers.map(member=>`<option>${esc(member.name)}</option>`).join("")}</select></label><label>기한<input name="due" value="오늘"></label><label>주기<select name="repeat"><option>없음</option><option>매일</option><option>3일마다</option><option>매주</option><option>매월</option></select></label>`,notice:`<label>제목<input name="title" required></label><label>내용<textarea name="body" required></textarea></label><label>작성자<select name="owner"><option>수희</option><option>엄마</option><option>아빠</option><option>동생</option></select></label><label><input name="important" type="checkbox"> 중요 공지로 표시</label><label><input name="private" type="checkbox"> 비밀번호 보호</label><label>비밀번호<input name="password" placeholder="비공개 글인 경우 입력"></label>`};document.getElementById("modal-root").innerHTML=`<div class="modal-backdrop"><div class="modal"><h2>${type==="ingredient"?"재료 추가":type==="event"?"일정 추가":type==="chore"?"집안일 TO-DO LIST 추가":"공지사항 작성"}</h2><form class="form" data-form="${type}">${fields[type]}<div class="modal-actions"><button type="button" class="secondary" data-close>취소</button><button type="submit" class="primary">저장</button></div></form></div></div>`}
function formValues(form){const values=Object.fromEntries(new FormData(form));form.querySelectorAll('input[type="checkbox"][name]').forEach(input=>{values[input.name]=input.checked});return values}
function saveForm(form){const d=formValues(form);const type=form.dataset.form;if(type==="ingredient"){const item={id:Date.now(),emoji:"🥕",...d};state.ingredients.push(item);recentlyAddedId=item.id}if(type==="event")state.events.push({id:Date.now(),...d});if(type==="chore")state.chores.push({id:Date.now(),done:false,...d});if(type==="notice")state.notices.unshift({id:Date.now(),title:d.title,body:d.body,owner:d.owner,private:d.private,password:d.password||"",important:d.important});save();document.getElementById("modal-root").innerHTML="";layout();if(type==="ingredient")window.setTimeout(()=>{recentlyAddedId=null;layout()},4200)}
function bind(){document.querySelectorAll("[data-go]").forEach(b=>b.onclick=()=>{view=b.dataset.go;layout()});document.querySelectorAll("[data-modal]").forEach(b=>b.onclick=()=>modal(b.dataset.modal));document.querySelectorAll("[data-toggle]").forEach(b=>b.onclick=()=>{const c=state.chores.find(x=>x.id==b.dataset.toggle);if(c){c.done=!c.done;save();layout()}});document.querySelectorAll("[data-delete]").forEach(b=>b.onclick=()=>{const k={ingredient:"ingredients",event:"events",chore:"chores",notice:"notices"}[b.dataset.delete];state[k]=state[k].filter(x=>x.id!=b.dataset.id);save();layout()});document.querySelectorAll("[data-page]").forEach(b=>b.onclick=()=>{window.noticePage=b.dataset.page;layout()});document.querySelectorAll("[data-view-notice]").forEach(b=>b.onclick=()=>{const n=state.notices.find(x=>x.id==b.dataset.viewNotice);if(n.private&&prompt("비밀번호를 입력하세요")!==n.password)return alert("비밀번호가 올바르지 않습니다.");alert(`${n.title}\n\n${n.body}`)});document.querySelectorAll("[data-photo]").forEach(b=>b.onclick=()=>alert("사진 선택 기능은 현재 UI 흐름이 연결되어 있습니다. 실제 저장/AI 인식은 다음 단계에서 연결합니다."));document.querySelector("[data-close]")?.addEventListener("click",()=>document.getElementById("modal-root").innerHTML="")}
document.getElementById("main-nav").onclick=e=>{const b=e.target.closest("[data-view]");if(b){view=b.dataset.view;layout()}};document.addEventListener("click",e=>{if(e.target.closest("[data-close]"))document.getElementById("modal-root").innerHTML=""});document.addEventListener("submit",e=>{const form=e.target.closest("[data-form]");if(form){e.preventDefault();saveForm(form)}});layout();
