/* Firebase-backed identity: current member, family brand, profile and administrator management. */
(function () {
  "use strict";
  const cloud = window.familyCloud;
  const settings = cloud.settings;
  const esc = value => String(value == null ? "" : value).replace(/[&<>"']/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
  const current = () => settings.members.find(m => m.username === cloud.username);
  const admin = () => current()?.role === "admin";
  // The system admin is not a family member: exclude it from every shared family view.
  const familyOnly = () => settings.members.filter(m => m.role !== "admin");
  window.familyIdentity = Object.freeze({ current, isAdmin: admin, members: familyOnly, brand: () => ({themeColor: settings.themeColor}) });
  const photo = value => /^(https:\/\/|data:image\/)/i.test(String(value || "")) ? String(value) : "";
  const avatar = m => photo(m.photo) ? `<img src="${esc(photo(m.photo))}" alt="">` : esc(m.avatar || m.name.slice(0,1));
  const logoMarkup = () => photo(settings.logoPhoto) ? `<img src="${esc(photo(settings.logoPhoto))}" alt="">` : esc(settings.logo || "LF");
  const errorText = error => error?.code === "auth/invalid-credential" || error?.code === "auth/wrong-password" ? "현재 비밀번호가 올바르지 않아요." : error?.code === "auth/email-already-in-use" ? "이미 로그인 계정이 있는 아이디예요. 비밀번호를 재설정하려면 Firebase Console > Authentication에서 해당 사용자를 먼저 삭제한 뒤 다시 만들어주세요." : error?.code === "auth/weak-password" ? "비밀번호는 6자 이상이어야 해요." : error?.code === "auth/too-many-requests" ? "시도가 너무 많아요. 잠시 후 다시 시도해주세요." : error?.code === "permission-denied" ? "권한이 없어요." : error?.message || "처리하지 못했어요.";
  const setStatus = (element, message, isError) => { element.textContent = message; element.classList.toggle("photo-error", Boolean(isError)); };
  const identityViewActive = view => document.querySelector(`[data-identity-view="${view}"].active`);
  function shell() {
    const me=current(); if(!me)return; const identityName=admin()?"관리자":me.name; document.title=settings.familyName; if(!document.querySelector("[data-identity-view].active")) document.getElementById("page-title").textContent=`안녕하세요, ${identityName}님`; document.querySelector(".brand strong").textContent=settings.familyName; const brandMark=document.querySelector(".brand-mark"); brandMark.innerHTML=logoMarkup(); brandMark.style.background=settings.themeColor; brandMark.setAttribute("role","button"); brandMark.setAttribute("tabindex","0"); brandMark.setAttribute("aria-label",admin()?"가족 브랜드 편집":"가족 브랜드 정보");
    document.getElementById("profile-summary").innerHTML=admin()?`<i style="background:#53626d">⚙</i><div><b>ADMIN</b><span>관리자 · 시스템 설정</span></div><button class="logout-btn" type="button">로그아웃</button>`:`<i style="background:${esc(me.color)}">${avatar(me)}</i><div><b>${esc(me.englishName||me.name)}</b><span>${esc(me.name)} · 가족 구성원</span></div><button class="logout-btn" type="button">로그아웃</button>`;
    document.querySelector(".logout-btn").onclick=()=>cloud.signOut(); const active=familyOnly().filter(m=>m.active); document.getElementById("family-card").innerHTML=`<div class="family-title"><span class="family-card-logo" style="background:${esc(settings.themeColor)}">${logoMarkup()}</span> ${esc(settings.familyName)} <b>${active.length}</b></div><div class="members">${active.map(m=>`<i style="background:${esc(m.color)}" title="${esc(m.name)}">${avatar(m)}</i>`).join("")}</div>`;
    const nav=document.getElementById("main-nav"), activeView=nav.querySelector("[data-identity-view].active")?.dataset.identityView; nav.querySelectorAll("[data-identity-view]").forEach(n=>n.remove()); const add=(view,label,icon,short=label)=>{const b=document.createElement("button");b.className=`nav-item${view===activeView?" active":""}`;b.dataset.identityView=view;b.type="button";b.title=label;b.innerHTML=`<span class="nav-icon" aria-hidden="true">${icon}</span><span class="nav-text nav-text-long">${label}</span><span class="nav-text nav-text-short">${short}</span>`;nav.appendChild(b);};if(admin())add("settings","설정","⚙","설정");else add("profile","내 프로필","●","MY");
  }
  function brandEditor() {
    const currentPhoto=photo(settings.logoPhoto); let selectedPhoto=currentPhoto;
    document.getElementById("modal-root").innerHTML=`<div class="modal-backdrop"><div class="modal"><h2>가족 브랜드 편집</h2><form class="form" id="brand-form"><label>가족/그룹 이름<input name="familyName" required maxlength="60" value="${esc(settings.familyName)}"></label><label>로고 글자 또는 이모지<input name="logo" maxlength="8" value="${esc(settings.logo||"LF")}"></label><div class="photo-picker"><span class="photo-label">로고 이미지</span><input class="photo-input" type="file" accept="image/jpeg,image/png,image/gif,image/webp,image/avif" data-brand-logo-input aria-label="가족 로고 이미지 선택"><div class="profile-photo-preview brand-logo-preview" data-brand-logo-preview>${currentPhoto?`<img src="${esc(currentPhoto)}" alt="현재 가족 로고">`:`<span>${esc(settings.logo||"LF")}</span>`}</div><div class="photo-actions"><button type="button" class="add-btn" data-brand-logo>사진 선택</button>${currentPhoto?`<button type="button" class="mini" data-remove-brand-logo>이미지 삭제</button>`:""}</div><p class="photo-status" data-brand-status role="status">JPG, PNG, GIF, WEBP, AVIF · 최대 5MB</p></div><label>테마/강조 색상<input name="themeColor" required maxlength="7" pattern="^#[0-9a-fA-F]{6}$" value="${esc(settings.themeColor)}"></label><p class="photo-status" data-brand-color-status role="status"></p><div class="modal-actions"><button type="button" class="secondary" data-brand-close>취소</button><button class="primary">저장</button></div></form></div></div>`;
    const form=document.getElementById("brand-form"), status=form.querySelector("[data-brand-status]"), colorStatus=form.querySelector("[data-brand-color-status]"), preview=form.querySelector("[data-brand-logo-preview]"), logoInput=form.querySelector("[data-brand-logo-input]");
    form.querySelector("[data-brand-logo]").onclick=()=>logoInput.click();
    logoInput.onchange=async event=>{const file=event.target.files?.[0];event.target.value="";if(!file)return;try{const result=await window.familyPhotoStorage.readPhoto(file,window.familyPhotoStorage.photoLimits.profileBytes);selectedPhoto=result.dataUrl;preview.innerHTML=`<img src="${esc(selectedPhoto)}" alt="선택한 가족 로고">`;setStatus(status,"이미지를 선택했어요. 저장 버튼을 눌러 적용하세요.");}catch(error){setStatus(status,error.message,true);}};
    form.querySelector("[data-remove-brand-logo]")?.addEventListener("click",()=>{selectedPhoto="";preview.innerHTML=`<span>${esc(form.logo.value||settings.logo||"LF")}</span>`;setStatus(status,"이미지를 삭제합니다. 저장 버튼을 눌러 적용하세요.");});
    form.querySelector("[data-brand-close]").onclick=()=>document.getElementById("modal-root").innerHTML="";
    form.onsubmit=async e=>{e.preventDefault();if(!admin())return;const values=Object.fromEntries(new FormData(form));if(!/^#[0-9a-f]{6}$/i.test(values.themeColor)){setStatus(colorStatus,"색상은 #RRGGBB 형식으로 입력해주세요.",true);form.themeColor.focus();return;}settings.familyName=values.familyName.trim();settings.logo=values.logo.trim()||"LF";settings.logoPhoto=selectedPhoto;settings.themeColor=values.themeColor.toLowerCase();try{await cloud.saveFamily();document.getElementById("modal-root").innerHTML="";shell();identityViewActive("settings")?settingsPage():window.layout?.();}catch(error){setStatus(colorStatus,errorText(error),true);}};
  }
  function profile() {
    if(admin())return settingsPage();
    const me=current();
    const existingPhoto=photo(me.photo);
    document.getElementById("page-title").textContent="내 프로필"; document.getElementById("page-subtitle").textContent="가족에게 보이는 내 정보와 비밀번호를 관리하세요.";
    document.getElementById("app-view").innerHTML=`<section class="page-grid"><article class="card wide"><div class="toolbar"><div><h2>내 프로필</h2><p class="subtitle">가족에게 보이는 내 정보를 관리하세요. 다른 가족 구성원의 정보는 수정할 수 없습니다.</p></div></div><form class="form identity-form" id="profile-form"><label>로그인 아이디<input value="${esc(me.username)}" disabled></label><label>한국어 표시 이름<input name="name" required maxlength="40" value="${esc(me.name)}"></label><label>영문 표시 이름<input name="englishName" maxlength="40" value="${esc(me.englishName||"")}"></label><label>아바타 글자<input name="avatar" maxlength="4" value="${esc(me.avatar||"")}"></label><div class="photo-picker"><span class="photo-label">프로필 사진</span><input class="photo-input" type="file" accept="image/jpeg,image/png,image/gif,image/webp,image/avif" data-profile-photo-input aria-label="프로필 사진 선택"><div class="profile-photo-preview" data-profile-preview>${existingPhoto?`<img src="${esc(existingPhoto)}" alt="현재 프로필 사진">`:`<span>${esc(me.avatar||me.name.slice(0,1))}</span>`}</div><div class="photo-actions"><button type="button" class="add-btn" data-profile-photo>사진 선택</button>${existingPhoto?`<button type="button" class="mini" data-remove-profile-photo>사진 삭제</button>`:""}</div><p class="photo-status" data-profile-status role="status">${existingPhoto?"현재 사진이 선택되어 있어요.":"JPG, PNG, GIF, WEBP, AVIF · 최대 5MB"}</p></div><label>내 테마 색상<input name="color" type="color" value="${esc(/^#[0-9a-f]{6}$/i.test(me.color)?me.color:"#d39a62")}"></label><p class="photo-status" data-profile-save-status role="status"></p><div class="modal-actions"><button class="primary">프로필 저장</button></div></form><form class="form identity-form password-form" id="password-form"><h3>비밀번호 변경</h3><label>현재 비밀번호<input name="current" type="password" autocomplete="current-password" required></label><label>새 비밀번호 (6자 이상)<input name="next" type="password" autocomplete="new-password" minlength="6" required></label><label>새 비밀번호 확인<input name="confirm" type="password" autocomplete="new-password" minlength="6" required></label><p class="photo-status" data-password-status role="status"></p><div class="modal-actions"><button class="primary">비밀번호 변경</button></div></form></article></section>`;
    const form=document.getElementById("profile-form");
    const status=form.querySelector("[data-profile-status]");
    let selectedPhoto=existingPhoto;
    form.querySelector("[data-profile-photo]").onclick=()=>form.querySelector("[data-profile-photo-input]").click();
    form.querySelector("[data-profile-photo-input]").onchange=async event=>{const file=event.target.files?.[0];event.target.value="";if(!file)return;try{const result=await window.familyPhotoStorage.readPhoto(file,window.familyPhotoStorage.photoLimits.profileBytes);selectedPhoto=result.dataUrl;form.querySelector("[data-profile-preview]").innerHTML=`<img src="${esc(selectedPhoto)}" alt="선택한 프로필 사진">`;setStatus(status,"사진을 선택했어요. 저장 버튼을 눌러 적용하세요.");}catch(error){setStatus(status,error.message,true);}};
    form.querySelector("[data-remove-profile-photo]")?.addEventListener("click",()=>{selectedPhoto="";form.querySelector("[data-profile-preview]").innerHTML=`<span>${esc(me.avatar||me.name.slice(0,1))}</span>`;setStatus(status,"사진을 삭제합니다. 저장 버튼을 눌러 적용하세요.");});
    form.onsubmit=async e=>{e.preventDefault();const values=Object.fromEntries(new FormData(form));const next={...me,name:values.name.trim(),englishName:values.englishName.trim()||values.name.trim().toUpperCase(),avatar:values.avatar.trim(),color:/^#[0-9a-f]{6}$/i.test(values.color)?values.color:"#d39a62",photo:selectedPhoto};try{await cloud.saveProfile(next);Object.assign(me,next);shell();profile();window.familyToast?.("프로필을 저장했어요.");}catch(error){setStatus(form.querySelector("[data-profile-save-status]"),errorText(error),true);}};
    const passwordForm=document.getElementById("password-form"), passwordStatus=passwordForm.querySelector("[data-password-status]");
    passwordForm.onsubmit=async e=>{e.preventDefault();const values=Object.fromEntries(new FormData(passwordForm));if(values.next.length<6){setStatus(passwordStatus,"새 비밀번호는 6자 이상이어야 해요.",true);return;}if(values.next!==values.confirm){setStatus(passwordStatus,"새 비밀번호가 서로 달라요.",true);return;}passwordForm.querySelectorAll("button,input").forEach(x=>x.disabled=true);try{await cloud.changePassword(values.current,values.next);passwordForm.reset();setStatus(passwordStatus,"비밀번호를 변경했어요.");}catch(error){setStatus(passwordStatus,errorText(error),true);}finally{passwordForm.querySelectorAll("button,input").forEach(x=>x.disabled=false);}};
  }
  // System settings: only the fixed system admin can open this page.
  function settingsPage(message = "") {
    if (!admin()) return profile();
    document.getElementById("page-title").textContent="설정"; document.getElementById("page-subtitle").textContent="가족 공간 전체를 관리하는 시스템 설정입니다.";
    const members=familyOnly();
    const hex=v=>/^#[0-9a-f]{6}$/i.test(v||"")?v:"#888888";
    const memberFields=members.map(m=>`<fieldset class="member-editor" data-member-id="${esc(m.id)}"><legend>${esc(m.name)} <span class="member-username">@${esc(m.username)}</span></legend><label>이름<input name="name-${esc(m.id)}" required maxlength="40" value="${esc(m.name)}"></label><label>영문 이름<input name="englishName-${esc(m.id)}" maxlength="40" value="${esc(m.englishName||"")}"></label><label>아바타 글자<input name="avatar-${esc(m.id)}" maxlength="4" value="${esc(m.avatar||"")}"></label><label>색상<input name="color-${esc(m.id)}" type="color" value="${esc(hex(m.color))}"></label><label class="checkbox-label"><input name="active-${esc(m.id)}" type="checkbox" ${m.active?"checked":""}> 활성 구성원 (해제 시 접근 불가)</label><button type="button" class="mini danger" data-remove-member="${esc(m.id)}">구성원 삭제</button></fieldset>`).join("")||`<div class="empty">아직 가족 계정이 없어요. 위에서 계정을 만들어주세요.</div>`;
    document.getElementById("app-view").innerHTML=`<section class="page-grid"><article class="card wide">
<section class="settings-section"><div class="toolbar"><div><h2>가족 공간</h2><p class="subtitle">이름, 로고, 테마 색상은 모든 가족에게 동일하게 보여요.</p></div><button type="button" class="secondary" data-open-brand>로고 이미지 변경</button></div><form class="form identity-form" id="space-form"><label>가족/그룹 이름<input name="familyName" required maxlength="60" value="${esc(settings.familyName)}"></label><label>로고 글자 또는 이모지<input name="logo" maxlength="8" value="${esc(settings.logo||"LF")}"></label><label>테마/강조 색상<input name="themeColor" type="color" value="${esc(hex(settings.themeColor))}"></label><p class="photo-status" id="space-status" role="status"></p><div class="modal-actions"><button class="primary">가족 공간 저장</button></div></form></section>
<section class="settings-section"><form class="member-create" id="member-create-form"><h3>＋ 가족 계정 만들기</h3><label>표시 이름<input name="name" required maxlength="40" placeholder="예: 엄마"></label><label>로그인 아이디<input name="username" required maxlength="30" autocapitalize="none" autocorrect="off" spellcheck="false" placeholder="예: mom (영문 소문자/숫자)"></label><label>초기 비밀번호 (6자 이상)<input name="password" type="text" required minlength="6" autocomplete="off" autocapitalize="none"></label><div class="form-actions"><button class="primary">계정 만들기</button><p class="photo-status" id="member-create-status" role="status">${esc(message)}</p></div><small class="credential-note" style="grid-column:1/-1">가족에게 아이디와 초기 비밀번호를 전달하고, 로그인 후 내 프로필에서 비밀번호를 바꾸도록 안내하세요. 비밀번호를 잊은 경우 Firebase Console &gt; Authentication에서 해당 사용자를 삭제한 뒤 같은 아이디로 다시 만들면 프로필은 유지된 채 새 비밀번호가 설정됩니다.</small></form></section>
<section class="settings-section"><h3>가족 구성원 관리 <small class="muted">(${members.length})</small></h3><form class="form identity-form" id="members-form"><div class="member-settings">${memberFields}</div><p class="photo-status" id="members-status" role="status"></p>${members.length?`<div class="modal-actions"><button class="primary">구성원 정보 저장</button></div>`:""}</form></section>
<section class="settings-section"><h3>시스템 정보</h3><p class="subtitle">관리자 계정: <b>admin</b> (고정) · 관리자는 가족 구성원 목록, 일정 담당자, 집안일 담당자에 표시되지 않아요.<br>AI 재료 인식은 Firebase AI Logic(Gemini)을 사용해요.</p></section>
</article></section>`;
    document.querySelector("[data-open-brand]").onclick=()=>brandEditor();
    const spaceForm=document.getElementById("space-form"), spaceStatus=document.getElementById("space-status");
    spaceForm.onsubmit=async e=>{e.preventDefault();if(!admin())return;const d=Object.fromEntries(new FormData(spaceForm));const previous={familyName:settings.familyName,logo:settings.logo,themeColor:settings.themeColor};settings.familyName=d.familyName.trim();settings.logo=d.logo.trim()||"LF";settings.themeColor=hex(d.themeColor).toLowerCase();try{await cloud.saveFamily();shell();window.layout?.();settingsPage();window.familyToast?.("가족 공간 설정을 저장했어요.");}catch(error){Object.assign(settings,previous);setStatus(spaceStatus,errorText(error),true);}};
    const createForm=document.getElementById("member-create-form"), createStatus=document.getElementById("member-create-status");
    createForm.onsubmit=async e=>{e.preventDefault();if(!admin())return;const d=Object.fromEntries(new FormData(createForm));const username=d.username.trim().toLowerCase();if(!/^[a-z0-9][a-z0-9._-]{1,29}$/.test(username)){setStatus(createStatus,"아이디는 영문 소문자/숫자로 시작하고 영문·숫자·. _ - 로 2~30자여야 해요.",true);return;}if(username==="admin"){setStatus(createStatus,"admin은 시스템 관리자 전용 아이디예요.",true);return;}if(d.password.length<6){setStatus(createStatus,"비밀번호는 6자 이상이어야 해요.",true);return;}createForm.querySelectorAll("button,input").forEach(x=>x.disabled=true);setStatus(createStatus,"계정을 만드는 중…");try{await cloud.createMember({username,password:d.password,name:d.name.trim()});settingsPage(`'${d.name.trim()}' 계정을 만들었어요. 아이디: ${username}`);window.familyToast?.("가족 계정을 만들었어요.");}catch(error){createForm.querySelectorAll("button,input").forEach(x=>x.disabled=false);setStatus(createStatus,errorText(error),true);}};
    const form=document.getElementById("members-form"), status=document.getElementById("members-status");
    form.querySelectorAll("[data-remove-member]").forEach(button=>button.onclick=async()=>{if(!admin())return;const member=members.find(m=>m.id===button.dataset.removeMember);if(!member)return;if(!confirm(`${member.name}(@${member.username}) 구성원을 삭제할까요? 삭제하면 이 계정으로 더 이상 접근할 수 없습니다.`))return;try{await cloud.removeMember(member.username);settingsPage("구성원을 삭제했어요. 같은 아이디를 다시 쓰려면 Firebase Console에서 해당 로그인 계정도 삭제해주세요.");}catch(error){setStatus(status,errorText(error),true);}});
    form.onsubmit=async e=>{e.preventDefault();if(!admin())return;const d=Object.fromEntries(new FormData(form));const previous=settings.members;settings.members=settings.members.map(m=>m.role==="admin"?m:{...m,name:d[`name-${m.id}`].trim()||m.name,englishName:d[`englishName-${m.id}`].trim(),avatar:d[`avatar-${m.id}`].trim(),color:hex(d[`color-${m.id}`]),active:d[`active-${m.id}`]==="on",role:"user"});try{await cloud.saveFamily();shell();settingsPage();window.familyToast?.("구성원 정보를 저장했어요.");}catch(error){settings.members=previous;setStatus(status,errorText(error),true);}};
  }
  if(!current()){window.familyToast?.("가족 구성원 정보를 찾을 수 없어요. 관리자에게 문의해주세요.");cloud.signOut();return;}
  shell();
  cloud.onChange(type=>{if(type!=="settings")return;if(!current())return;shell();const idle=!document.activeElement?.closest("form");if(identityViewActive("profile")&&idle)profile();if(identityViewActive("settings")&&idle)settingsPage();});
  const brand=document.querySelector(".brand-mark"); brand.onclick=()=>{if(admin())brandEditor();}; brand.onkeydown=e=>{if((e.key==="Enter"||e.key===" ")&&admin()) {e.preventDefault();brandEditor();}};
  document.getElementById("main-nav").addEventListener("click",e=>{const b=e.target.closest("[data-identity-view]");if(!b)return;e.preventDefault();e.stopImmediatePropagation();const identityView=b.dataset.identityView;if(identityView==="settings"&&!admin())return;if(identityView==="profile"&&admin())return;document.querySelectorAll(".nav-item").forEach(n=>n.classList.toggle("active",n===b));identityView==="settings"?settingsPage():profile();window.scrollTo(0,0);},true);
  document.getElementById("profile-summary").onclick=e=>{if(e.target.closest(".logout-btn"))return;const target=admin()?"settings":"profile";document.querySelectorAll(".nav-item").forEach(n=>n.classList.toggle("active",n.dataset.identityView===target));admin()?settingsPage():profile();};
  window.layout?.();
})();
