/* Local-only identity seam. Replace authenticate() and storage adapters with API calls later. */
(function () {
  "use strict";
  const authKey = "lee-family-auth", settingsKey = "lee-family-settings";
  const defaults = { familyName: "LEE_FAMILY", logo: "LF", members: [
    {id:"suhui",name:"소희",englishName:"SOHEE",avatar:"소희",color:"#d39a62",activeCount:2,role:"admin",active:true,username:"suhui",password:"1234"},
    {id:"mom",name:"엄마",avatar:"엄마",color:"#9a7899",activeCount:1,role:"user",active:true,username:"mom",password:"1234"},
    {id:"dad",name:"아빠",avatar:"아빠",color:"#7595ad",activeCount:1,role:"user",active:true,username:"dad",password:"1234"},
    {id:"sibling",name:"동생",avatar:"동생",color:"#6ea38f",activeCount:0,role:"user",active:true,username:"sibling",password:"1234"}
  ]};
  const esc = value => String(value == null ? "" : value).replace(/[&<>"']/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
  const read = (key, fallback) => { try { return JSON.parse(localStorage.getItem(key) || "null") || fallback; } catch (_) { return fallback; } };
  let settings = read(settingsKey, defaults); settings = {...defaults,...settings,members:Array.isArray(settings.members) ? settings.members : defaults.members};
  let session = read(authKey, null);
  const current = () => settings.members.find(m => m.id === session?.memberId);
  const admin = () => current()?.role === "admin";
  window.familyIdentity = Object.freeze({ current, isAdmin: admin });
  const save = () => localStorage.setItem(settingsKey, JSON.stringify(settings));
  const photo = value => /^(https:\/\/|data:image\/)/i.test(String(value || "")) ? String(value) : "";
  const avatar = m => photo(m.photo) ? `<img src="${esc(photo(m.photo))}" alt="">` : esc(m.avatar || m.name.slice(0,1));
  // Replace this adapter with the future authentication API.
  const authenticate = (username, password) => { const found = settings.members.find(m => m.username === username && m.password === password && m.active); return found && {memberId:found.id}; };
  function login() {
    document.querySelector(".app").style.display = "none";
    document.getElementById("modal-root").innerHTML = `<main class="login-screen"><form class="login-card" id="login-form"><div class="brand-mark">${esc(settings.logo)}</div><p class="eyebrow">FAMILY HUB</p><h1>${esc(settings.familyName)}</h1><p class="subtitle">가족 계정으로 로그인하세요.</p><label>아이디<input name="username" autocomplete="username" required placeholder="예: suhui"></label><label>비밀번호<input name="password" type="password" autocomplete="current-password" required placeholder="데모 비밀번호: 1234"></label><p class="login-error" id="login-error" role="alert"></p><button class="primary">로그인</button><small class="login-help">데모 계정: suhui / 1234 (관리자), mom / 1234</small></form></main>`;
    document.getElementById("login-form").onsubmit = e => { e.preventDefault(); const d=Object.fromEntries(new FormData(e.currentTarget)), next=authenticate(d.username.trim(),d.password); if(!next){document.getElementById("login-error").textContent="아이디 또는 비밀번호를 확인해주세요.";return;} session=next;localStorage.setItem(authKey,JSON.stringify(session));location.reload(); };
  }
  function shell() {
    const me=current(); document.title=settings.familyName; document.getElementById("page-title").textContent=`안녕하세요, ${esc(me.name)}님`; document.querySelector(".brand strong").textContent=settings.familyName; document.querySelector(".brand-mark").textContent=settings.logo||"LF";
    document.getElementById("profile-summary").innerHTML=`<i style="background:${esc(me.color)}">${avatar(me)}</i><div><b>${esc(me.englishName||me.name)}</b><span>${esc(me.name)} · ${me.role==="admin"?"가족 관리자":"가족 구성원"}</span></div><button class="logout-btn" type="button">로그아웃</button>`;
    document.querySelector(".logout-btn").onclick=()=>{localStorage.removeItem(authKey);location.reload();}; const active=settings.members.filter(m=>m.active); document.getElementById("family-card").innerHTML=`<div class="family-title">함께하는 가족 <b>${active.length}</b></div><div class="members">${active.map(m=>`<i style="background:${esc(m.color)}">${avatar(m)}</i>`).join("")}</div>`;
    const nav=document.getElementById("main-nav");nav.querySelectorAll("[data-identity-view]").forEach(n=>n.remove()); const add=(view,label,icon)=>{const b=document.createElement("button");b.className="nav-item";b.dataset.identityView=view;b.innerHTML=`<span>${icon}</span>${label}`;nav.appendChild(b);};add("profile","내 프로필","●");if(admin())add("settings","가족 설정","⚙");
  }
  function profile() {
    const me=current();
    const existingPhoto=photo(me.photo);
    document.getElementById("app-view").innerHTML=`<section class="page-grid"><article class="card wide"><div class="toolbar"><div><h2>내 프로필</h2><p class="subtitle">가족에게 보이는 내 정보를 관리하세요.</p></div></div><form class="form identity-form" id="profile-form"><label>표시 이름<input name="name" required maxlength="40" value="${esc(me.name)}"></label><label>아바타 글자<input name="avatar" maxlength="4" value="${esc(me.avatar||"")}"></label><div class="photo-picker"><span class="photo-label">프로필 사진</span><input class="photo-input" type="file" accept="image/*" data-profile-photo-input aria-label="프로필 사진 선택"><div class="profile-photo-preview" data-profile-preview>${existingPhoto?`<img src="${esc(existingPhoto)}" alt="현재 프로필 사진">`:`<span>${esc(me.avatar||me.name.slice(0,1))}</span>`}</div><div class="photo-actions"><button type="button" class="add-btn" data-profile-photo>사진 선택</button>${existingPhoto?`<button type="button" class="mini" data-remove-profile-photo>사진 삭제</button>`:""}</div><p class="photo-status" data-profile-status role="status">${existingPhoto?"현재 사진이 선택되어 있어요.":"JPG, PNG, GIF, WEBP, AVIF · 최대 5MB"}</p></div><label>색상<input name="color" type="color" value="${esc(/^#[0-9a-f]{6}$/i.test(me.color)?me.color:"#d39a62")}"></label><div class="modal-actions"><button class="primary">프로필 저장</button></div></form></article></section>`;
    const form=document.getElementById("profile-form");
    const status=form.querySelector("[data-profile-status]");
    let selectedPhoto=existingPhoto;
    form.querySelector("[data-profile-photo]").onclick=()=>form.querySelector("[data-profile-photo-input]").click();
    form.querySelector("[data-profile-photo-input]").onchange=async event=>{const file=event.target.files?.[0];event.target.value="";if(!file)return;try{const result=await window.familyPhotoStorage.readPhoto(file,window.familyPhotoStorage.photoLimits.profileBytes);selectedPhoto=result.dataUrl;form.querySelector("[data-profile-preview]").innerHTML=`<img src="${esc(selectedPhoto)}" alt="선택한 프로필 사진">`;status.textContent="사진을 선택했어요. 저장 버튼을 눌러 적용하세요.";status.classList.remove("photo-error");}catch(error){status.textContent=error.message;status.classList.add("photo-error");}};
    form.querySelector("[data-remove-profile-photo]")?.addEventListener("click",()=>{selectedPhoto="";form.querySelector("[data-profile-preview]").innerHTML=`<span>${esc(me.avatar||me.name.slice(0,1))}</span>`;status.textContent="사진을 삭제합니다. 저장 버튼을 눌러 적용하세요.";});
    form.onsubmit=e=>{e.preventDefault();Object.assign(me,Object.fromEntries(new FormData(form)));me.photo=selectedPhoto;save();shell();profile();};
  }
  function family() { if(!admin())return profile(); document.getElementById("app-view").innerHTML=`<section class="page-grid"><article class="card wide"><div class="toolbar"><div><h2>가족 설정</h2><p class="subtitle">관리자만 가족 정보와 구성원을 수정할 수 있습니다.</p></div></div><form class="form identity-form" id="family-form"><label>가족/그룹 이름<input name="familyName" required maxlength="60" value="${esc(settings.familyName)}"></label><label>가족 로고 글자<input name="logo" maxlength="4" value="${esc(settings.logo)}"></label><div class="member-settings">${settings.members.map(m=>`<fieldset class="member-editor"><legend>${esc(m.name)}</legend><label>이름<input name="name-${m.id}" required maxlength="40" value="${esc(m.name)}"></label><label>아바타<input name="avatar-${m.id}" maxlength="4" value="${esc(m.avatar||"")}"></label><label>사진 URL<input name="photo-${m.id}" type="url" value="${esc(m.photo||"")}"></label><label>색상<input name="color-${m.id}" type="color" value="${esc(/^#[0-9a-f]{6}$/i.test(m.color)?m.color:"#888888")}"></label><label>활성 할 일 수<input name="activeCount-${m.id}" type="number" min="0" max="999" value="${Number(m.activeCount)||0}"></label><label class="checkbox-label"><input name="active-${m.id}" type="checkbox" ${m.active?"checked":""}> 활성 구성원</label></fieldset>`).join("")}</div><div class="modal-actions"><button class="primary">가족 설정 저장</button></div></form></article></section>`;document.getElementById("family-form").onsubmit=e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget));settings.familyName=d.familyName;settings.logo=d.logo;settings.members=settings.members.map(m=>({...m,name:d[`name-${m.id}`],avatar:d[`avatar-${m.id}`],photo:d[`photo-${m.id}`],color:d[`color-${m.id}`],activeCount:Math.max(0,Number(d[`activeCount-${m.id}`])||0),active:d[`active-${m.id}`]==="on"}));save();shell();family();}; }
  if(!session||!current()){login();return;} shell(); document.getElementById("main-nav").addEventListener("click",e=>{const b=e.target.closest("[data-identity-view]");if(!b)return;e.preventDefault();e.stopImmediatePropagation();document.querySelectorAll(".nav-item").forEach(n=>n.classList.toggle("active",n===b));b.dataset.identityView==="settings"?family():profile();},true); document.getElementById("profile-summary").onclick=e=>{if(!e.target.closest(".logout-btn"))profile();}; window.layout?.();
})();